### ISSUE TITLE
Define scope / MVP for Open Ulmus platform

### ISSUE THREAD

**Issue by btopro** [elmsln/openulmus.org#1]
https://docs.google.com/document/d/1ogL5VKRNAfJMfAybztRL2EJ2-Sx3NBsT3ZErNYU1gXY/edit?usp=sharing has a bunch of this throughout but we need a solid 1 paragraph of what this is and why it's useful.

Key For Launch of Open Ulmus:
- [x] Initial Training Defined #6 
- [ ] Roles #2 
- [x] Social Media Presence #18 
- [x] Open Ulmus Collective Created #25 
- [x] Branding Website #27 
- [x] Budget #23 
- [ ] Initial Training Course Outline #29 
- [ ] Build Proof of Concept ELMS:LN Course (#6 & #7)
- [ ] Logo

Time & Cost Estimate for MVP:
- Branding Site Creation: 30 hours / $2250 
- Initial Training Outline: 5 hours / $375
- Initial Training Build: 20 hours / $1,500
- Initial Logo Design 10 hours / $750 
- Product Management Tasks / $3,600 - divided by 3(?) = $1,200 per person for 2 months of admin

### Total: $4,875

Post Launch Tasks:
- Set up Mail #28 
- Tiers #24 
- Instance Request Flow #21 
-  Logo #26 
- Collective Hosting (OpenCollective vs. Self)

**Comment by gusaus** [comment]
I cleaned up the doc a bit, but feel free to rearrange, fill in the blanks, and make it logical.  With regards to MVP, is it standard ELMS + OpenCollective integrations such as [Tracking community engagement](https://github.com/opencollective/opencollective-api/issues/793) and [Advertisement for project sponsors](https://github.com/opencollective/opencollective-api/issues/769)? Will we be incorporating [LRN WebComponents](https://github.com/LRNWebComponents) and other features/functionality not yet in standard ELMS? 

I guess that's some of what we'll figure out in this doc!

**Comment by btopro** [comment]
Definitely somethings to figure out in the doc. ELMSLN has LRN baked all across the platform tho so that part is a [x] :)

**Comment by gusaus** [comment]
@btopro The google doc linked in the issue description needs to be swapped out with this -
https://docs.google.com/document/d/1ogL5VKRNAfJMfAybztRL2EJ2-Sx3NBsT3ZErNYU1gXY/edit?usp=sharing

Unless there's actually a better way to scope these sites in the open?!?

**Comment by mmilutinovic013** [comment]
Based off @gusaus ' commend on slack I am going to create a new issue with discussions we need to have before a release is possible. Eventually I'll switch this over to sprint tags...but for now, I want to capture my thoughts in a checklist

**Comment by gusaus** [comment]
I wanna add this related convo from #drupalopenlearning (Drupal Slack) before it disappears:

From gusaus

> @btopro Can you refresh my memory regarding how we can use ELMS / Open Ulmus for Drupal Open Learning projects.
> 
> For example, let's say we're ready to begin what is poorly described here - https://github.com/DrupalOpenLearning/administration/issues/8
> 
> Would that reside somewhere on https://online.openulmus.org/ or could it be on say a subdomain of http://drupalopenlearning.org/
> 
> Possibly I've completely forgotten how this could work :grinning:

From btopro 

> @gusaus so we typically treat that online site like a backend management system. It helps us orchestrate and produce courses
> 
> Then we add a course there and say “hey this has content” so it creates a content space for it
> in the case of Drupal open learning, this then would be told to be a public space anyone can use
> 
> think of it like a multi-site factory that’s cranking out drupal sites that are heavily configured in a certain direction and then can be tweaked from there as needed
> 
> for example: http://stem-researchethics.org/edsr002/ is an Open research ethics resources powered by ELMSLN but it doesn’t actually live at that domain
> 
> it has a normal “courses.whatever” style address but then we point the vanity domain over to it

From gusaus [12:31 PM] 

> @btopro What you just described there sounds like a great intro to a how we're using ELMS for Drupal Open Learning - whoever is the ID/PM mentor for the project can fire up Twitch to show folks how it's done - possibly pair up with an apprentice to do the actual setup. Each little working session can be archived as a Drupal Dojo session. :ninja:


From btopro [12:32 PM] 

> cool dood
> 
> when u get a point person let me know; we def have the stuff there to at minimum make a nice little housing for some trainings / walkthroughs as well as things to help with self-check exercises / interactive question building
> 
> the little xAPI course demonstrates that stuff throughout if you’ve clicked around


From gusaus [12:39 PM] 

> I was thinking more of the ID/PM mentor role as we were discussing here - https://github.com/DrupalOpenLearning/administration/issues/8#issuecomment-319501601
> 
> Not sure if Katrina has current availability/interest, but the point person would be more on the ELMS side?


From btopro [12:40 PM] 

> well, someone to make courses, ask questions, etc
> 
> to get up and going I dont think u need someone to build new functionality; you need someone to start setting up stuff in it and come up w/ areas they need new functionality
> 
> I mostly just mean like I can’t be the point person on it cause our team needs to stay focused on build mode for the platform, fixing bugs ppl find and improving author UX
> 

from gusaus [12:48 PM] 

> Sure - so if Mark is still tasked with https://github.com/elmsln/openulmus.org/issues/2 possibly he can find some point people (and help run the Twitch sessions?) - if our needs are clear I think Drupal Dojo will be a good vehicle for seeking out contributors and other types of support we need

We're touching on multiple issues in this convo, but with regards to my first question regarding "ELMS / Open Ulmus for Drupal Open Learning (website and projects)", is the MVP we're attempting to scope out here a product or distribution (in Drupal terms)?

Similarly, if one of the many OSS projects in wants their own instance of Open Ulmus for their own site/training program as we touched on here https://github.com/elmsln/openulmus.org/issues/2#issuecomment-328946587, will this MVP be the base product?

**Comment by gusaus** [comment]
Following up on a couple bits from the @btopro convo https://github.com/elmsln/openulmus.org/issues/1#issuecomment-331521363 

> is the MVP we're attempting to scope out here a product or distribution (in Drupal terms)? 

i.e. we could set up an 'Open Ulmus' project on d.o. if there was good reason to do that?

**Comment by mmilutinovic013** [comment]
We will be building #7 as the first priority of this scope. We need the following resources and discussions to occur to begin. 

- [ ] Course Objectives (What do people hope to get out of this course? Skills? Certificate? Etc?)
- [ ] Course Content (How long? What types of media? Exams? Activities?)
- [ ] Budget (Where is the budget coming from? Which collectives are in scope? Hourly vs. Set amount?)
- [ ] Content Release Date (When is it? Who is reviewing content? Will course be tested on group for feedback?)
- [ ] Release (When is it? How do we advertise it? What does it cost? Etc.)

**Comment by gusaus** [comment]
https://www.udemy.com/ is probably not the best example, but illustrates some of the functionality (search by category, top courses, become an instructor, etc.) that I'd think we'd want for https://openulmus.org/

I'm assuming incorporate some of these elements on the Open Ulmus site?

**Comment by mmilutinovic013** [comment]
That seems reasonable to me. openulmus.org would be the landing page then. That could be used to advertise the courses that live in its system. I will add additional issues/tasks in getting that site created.

**Comment by mmilutinovic013** [comment]
If my role is responsible for this, then this is the vision I see: 

1) Landing page of open ulmus describing what it is, how it works, and courses offered
2) courses powered by elmsln (first one being  about how open ulmus works)
3) Some advertisement for the collective so that we can keep the platform running and pay contributors for their efforts

**Comment by gusaus** [comment]
@cleverington this Drupal-Dojo-Collaboration folder you shared with the templates and our high level doc, and subfolders. Is this intended for our high level organization and workflows or will there be a folder like this for every open learning project? Maybe both?

As I think all these resources would reside on Open Ulmus, possibly we should rename or dup this folder Open-Ulmus-Collaboration as a way to better organize the scoping of and collab of this project?

**Comment by cleverington** [comment]
Honestly I was just drafting out some plans and thoughts, for content I assume will end up on OpenUlmus?

**Comment by mmilutinovic013** [comment]
I think that makes sense with the flow of open ulmus encompassing these other projects :)

**Comment by gusaus** [comment]
So why don't we rename or dup the folder and share with the Open Ulmus project team -
https://github.com/elmsln/openulmus.org/wiki/(2)-Open-Ulmus-Core-Team

**Comment by cleverington** [comment]
Folder name updated.  As mentioned in Slack though, I was using the folder more for a gathering of ideas as my knowledge-base on the project onboarded better.  ^-^

I just had to share it via folder because draw.io was being *weird*.

**Comment by mmilutinovic013** [comment]
So as far as roles go - How about we separate it into Program team (hat wearing essential roles to start the initiative) and Project team roles such as developers, IDs, etc. that can be added in once the initiative is built?

**Comment by mmilutinovic013** [comment]
If we lock this down - I think that we are in a good place to resolve #2

**Comment by gusaus** [comment]
So random question that I may have asked before… when Open Ulmus to the point of MVP - is that going to be something that can be downloaded - like a product or drupal distribution?  I know it’s going to be mainly ELMSLN, but there are probably going to be different features, the primary domain/landing pages would be different…uhhh… does that sorta makes sense?

**Comment by btopro** [comment]
everything made towards it should be open


[4:21] 
for example: Adding support for a payment gateway to buy courses; that sounds like a great add on to elmsln


[4:22] 
contributed to elmsln core as an optional module, lives there; hey download elmsln if u want to run ur own stack


[4:22] 
if ur talking little marketing sites and what not; if part of that is getting GravCMS into ELMS:LN core; then that’s part of the contribution


[4:23] 
the specifics of language and icons used in that theme to market the thing; that can live in a repo of it’s own as like a “hey here’s some customization we did to elmsln to use it for our purposes”

**Comment by gusaus** [comment]
@btopro Based on what you're saying above, I recommend the following - 

- [x] we set up a collective for Open Ulmus https://github.com/elmsln/openulmus.org/issues/25
- [ ] we direct our fundraising efforts (once we put together a plan) to https://opencollective.com/elmsln as mentioned in https://github.com/elmsln/openulmus.org/issues/22#issuecomment-341850611

Does that sound like a good approach?

**Comment by btopro** [comment]
yup

**Comment by gusaus** [comment]
I think we need to incorporate the comments and diagram regarding digital infrastructure into our scoping doc.
https://github.com/elmsln/openulmus.org/issues/7#issuecomment-342698982
https://github.com/elmsln/openulmus.org/issues/7#issuecomment-342841944
https://github.com/elmsln/openulmus.org/issues/7#issuecomment-342850619
https://drive.google.com/file/d/149Ps_j6J2_MqHJh-0WskYwI8-jNcDbWV/view

**Comment by gusaus** [comment]
With regards to the digital infrastructure as outlined here -  

![open-learning-collective_digital-infrastructure html - draw io 2017-11-09 19-09-20](https://user-images.githubusercontent.com/113996/32641202-7ed88156-c581-11e7-9639-5ef61876677e.png)

Are those intended to be working groups that can leverage Open Ulmus to create their own community courses and training? If so, it seems like the platform we're building for Drupal Dojo (which will be a child distribution of Open Social https://www.drupal.org/project/social) could provide the framework for powering those types of groups. https://github.com/DrupalOpenLearning/drupaldojo/issues/23

If that's a possibility, we should include the Dojo platform in the overall Open Ulmus scope https://github.com/DrupalOpenLearning/drupaldojo/issues/4

**Comment by mmilutinovic013** [comment]
I believe this is the intent. That subset (of course) is merely the Drupal subset. But it'd allow for FOSS communities to organize into sub-communities under a common platform.

**Comment by gusaus** [comment]
Right - so if we include the Dojo flavor of Open Social in the Open Ulmus network, other FOSS communities will be able to use to organize their own community.

**Comment by gusaus** [comment]
In an attempt to clarify how this community enabling child distribution of Open Social could eventually be part of the Open Ulmus offering. https://github.com/elmsln/openulmus.org/issues/1#issuecomment-343364964

Maybe we should call the potential product 'Open Ulmus Community', 'ELMS:LN Community', 'Open Social Education' or something that better describes the primary use case. 

We should include the Drupal Dojo site in our project scope since it will enable us to configure the site and include features/functionality that can extend to Open Ulmus (and vice versa). 

As we've already included Drupal Dojo collective as a way to sustain our team, consolidating the project scope should not introduce any additional responsibilities or scope creep. If anything we'll be able to make better use of the largest community in Drupal (https://groups.drupal.org/drupal-dojo) as a way to bring in additional contributors and sustainers for all our projects.

**Comment by gusaus** [comment]
This snippet of a conversation with one of the Open Social leads may provide a sense that there is already potential overlap between Open Social and ELMS:LN. 
![slack - drupal 2017-11-10 20-01-54](https://user-images.githubusercontent.com/113996/32686027-014d89da-c652-11e7-9903-d5fcc19fdc6e.png)

The case study and public roadmap should provide further insight - 
https://www.getopensocial.com/showcases/pachamama-alliance
https://receptive.io/app/#/graphical-roadmap/72a2bdb4-1b62-4875-974a-0e93899a4a29

**Comment by mmilutinovic013** [comment]
Perhaps we can make a similar roadmap for Open Ulmus. I think it would be beneficial to see if we could coordinate with their group to see if they would like to integrate into our system (potentially for their bigger clients that would need bigger EDU platforms).

**Comment by gusaus** [comment]
If moving forward with 'ELMS:LN' as a stand-alone, ongoing class  https://github.com/openulmus/openulmus.org/issues/6#issuecomment-369710503 the time/cost estimates can be decoupled from the Open Ulmus MVP https://github.com/openulmus/openulmus.org/issues/1#issue-242679421 and moved to https://github.com/openulmus/openulmus.org/issues/29

In doing so, the only outstanding tasks.. in what I think we consider the initial phase of Open Ulmus, would be the logo #26 and some tweaks to the live marketing site https://github.com/openulmus/openulmus.org/issues/34

The features/functionality, guidelines/docs, and plan to sustain can be considered stuff we'll work into the Phase II scope of work (we do have a google doc referenced in the issue description https://github.com/openulmus/openulmus.org/issues/1#issue-242679421). All of which can be built and delivered alongside other related projects by Open Learning Labs https://github.com/openlearninglabs/administration/issues/6

As ELMS:LN and Open Ulmus are [projects](https://github.com/openlearninglabs/administration/wiki/Projects), securing the budget for all phases of the project (including completed work) should be considered a responsibility of Open Learning Labs.

If any of this seems to contradict previous discussions and understanding regarding overall Open Ulmus scope, I'd circle back and chime in here https://github.com/openulmus/openulmus.org/issues/58

**Comment by gusaus** [comment]
Picking up on this comment from @btopro a ways back in Slack -

>fyi we are working a lot of HAX as desktop app, this is a really important thing to get people to write content seemlessly and do it in a CMS-less format

>we’re trying to make the ultimate desktop app for writing FOSS documentation which is a side benefit to what we really need it for but both efforts directly benefit authoring course / training curriculum

Assuming all the amazing that's being discussed is related....
http://news.psu.edu/story/522190/2018/05/18/academics/hax-revolutionize-online-course-authoring-education-technology

Is any of this functionality available or still a work in progress? If the latter, are there ways we can use this open platform build to onboard contributors?

**Comment by btopro** [comment]
hype != product https://github.com/LRNWebComponents/hax-desktop-app is a thing that you can take and do an `npm install` and spin up for local development and see where it's at. This would be a good place for you to onboard contributors or at least to get experience with the concept and what it's doing.

**Comment by gusaus** [comment]
I've been doing a pretty good job talking this up to several groups/initiatives in Drupal and OpenCollective. The interest/demand is extremely high!

That said, we've been unable to move anything forward without a completed project scope and a dedicated project manager. If there's nobody already involved with ELMS:LN available to fill those roles, I think a company that already has a vested interest and resources for providing estimates, dev tools, documentation, mentoring, and potentially hosting PaaS would be the best candidate to take the lead and receive whatever benefits (logo displayed all over the place, video/podcast spots, contributors to this OSS platform etc.) would be considered a good return. 

🤔

**Comment by btopro** [comment]
there's plenty of scoping and tons of talk about doing this but little action in awhile. If pantheon is offering what you just proposed then you should move people in that direction, it just won't be called open ulmus. (tone: if that's what you want to do and have the best shot of doing for your drupal open learning thing)

We honestly do very little drupal anymore, if that's the best path for your DOL thing then please go do that. Open ulmus via elms:ln + hax is on it's own trajectory, if it ends up aligning in the futre cool, if not then that's fine. If you are pinging these threads to try and get me to more actively pursue these efforts directly then it will not occur. I have a wheelhouse and am sticking to it, eventually, open ulmus and open, free training will just occur because of other projects but it will not be overprioritized in our roadmap to shift things ahead faster at the expense of our real needs and directions at penn state. The two are not the same (to get this in writing somewhere) but obviously the open contributions of one help build up the other.

**Comment by gusaus** [comment]
I kinda thought my last comment was a bit too mysterious - was actually referring to DRUD/DDEV  since there's a lot of overlap/compliment in terms of tools, resources, and market opportunity. Main reason I've circled back here is our [conversations over twitter](https://twitter.com/gusaus/status/999772063815499776) has directly led to @rickmanelius taking the first step in making it easier to develop/deploy ELMS:LN https://github.com/openulmus/openulmus.org/issues/48#issuecomment-396239207 and potentially our GravCMS based https://openulmus.org/ https://github.com/openulmus/openulmus.org/issues/48#issuecomment-396415511

If we have this type of dev/deploy flow (https://www.drud.com/what-is-ddev/), it would be easier to move forward with the suggested plan above https://github.com/openulmus/openulmus.org/issues/1#issuecomment-369738844. Especially if a PM/mentor type could [pick up on this topic](https://www.drud.com/events/come-on-the-journey-from-rfp-to-release-at-drupalcon-nashville/) and scope/estimate Open Ulmus as a learning project. 

Considering ELMS:LN, Open Ulmus, and Drupal are on OpenCollective, I personally would like to focus back on leveraging OpenCollective to sustain and grow each project. Assuming OC is pretty under the radar - https://medium.com/open-collective/may-newsletter-open-collective-d4292cfa0d48
