### ISSUE TITLE
Determine Open Ulmus operating budget

### ISSUE THREAD

**Issue by mmilutinovic013** [elmsln/openulmus.org#15]
Budget needs to be defined for the following: 

- [x] How does AWS get paid for? #12 
-  $7-9 bucks a month 
- A few $1K a month once things get rolling...
- [x] Who is the umbrella collective? #12
- Open Learning Labs
- [x] How do contributors/mentors get paid? #5
- Paid by collective they are aligned to. 
- Budget set at 40 hours/month (80 for dojo) 
- Estimated cost $4000-8000 labor costs per month
- [x] How do courses generate money back to their collectives? #12 
- From the service provider/sponsor
- Additional hosting costs are subtracted from course costs

**Comment by mmilutinovic013** [comment]
As per the discussion on #12 I propose that we use an Open Ulmus Collective to: 

1. Pay Contributors/Mentors
2. Generate Money for collectives hosting sites on open Ulmus
3. Generate money for ELMS:LN which pays for open Ulmus living on AWS.

We should talk about the initial budget and how mentors/interns would be funded when that would occur, and if there are any logistical hoops to jump through to get that started. 

Finally, we need to have someone come up with a way to advertise that collectives can earn money for their collectives by creating/hosting courses on open ulmus.

**Comment by gusaus** [comment]
We probably should first get a sense for the baseline cost needed to operate and sustain the program.

- What is the current monthly AWS cost? 
- What are the essential roles needed to operate Open Ulmus and is there a certain amount of total hours/month we should allocate? https://github.com/elmsln/openulmus.org/issues/2
- What are other costs we need to cover?

@mmilutinovic1313 Do we need someone to help w/ budgets and overall biz/organizational matters?

**Comment by mmilutinovic013** [comment]
- @btopro  would have a better idea of the AWS cost.
- I am adding additional roles of Instructional Designer (which will be defined by the collective requesting a course) as well as combining Webmaster and AWS person roles. 
- Other costs...Supporting collectives most likely? This provides an incentive for them to use Open Ulmus as a platform (and potentially invest people in improving the ELMS:LN backend.

**Comment by btopro** [comment]
@mmilutinovic1313 thus far I've been paying like 7 - 9 bucks a month... granted, there's like nothing on it so I can't help ya too much there. 100$ is enough to get started and go from there but your talking a few K when it all gets going

**Comment by gusaus** [comment]
Would it be better to first determine staffing and budget requirements needed to manage the program? If so, this is another case where there could be shared roles between Open Ulmus and Drupal Open Learning? https://github.com/DrupalOpenLearning/administration/issues/1

**Comment by mmilutinovic013** [comment]
Looks like when #5 and #12 are resolved we can close this.

**Comment by gusaus** [comment]
@mmilutinovic1313 Per https://github.com/elmsln/openulmus.org/issues/15#issuecomment-337996859 and https://github.com/elmsln/openulmus.org/issues/2#issuecomment-338299585 I think we need to determine staffing and budget requirements needed to manage the program. Should we create a stand-alone wiki page similar to https://github.com/DrupalOpenLearning/administration/wiki/Drupal-Open-Learning-program-staff and then add some specificity to the funding scenarios listed in https://github.com/elmsln/openulmus.org/issues/12#issuecomment-336339995?

**Comment by mmilutinovic013** [comment]
Yep - let’s do that. I’ll assign myself to that task and we can coordinate that tonight. Do we want to advertise potential pay rates to attract more contributors? Or shall we hold off on that?

**Comment by gusaus** [comment]
Let's start by getting a sense for the roles & total monthly amount of person hours per role needed to keep Open Ulmus operational.

**Comment by mmilutinovic013** [comment]
We need to work on #5 to help resolve this issue. With #5 clarified -- this ticket will be closer to complete and our scope / budget will be clearer :)

**Comment by mmilutinovic013** [comment]
Verifying that we can close this. I am I can add this info to the wiki and other related issues.

**Comment by gusaus** [comment]
Reopening and revising the [checklist above](https://github.com/openulmus/openulmus.org/issues/15#issue-264798558) to reflect changes needed to ensure 501c3 status via Open Collective Foundation #57
