### ISSUE TITLE
Fundraising: MOSS - Mission Partners

### ISSUE THREAD

**Issue by cleverington** [elmsln/openulmus.org#33]
## Recommendation

Let's get some funding!  The *Mozilla Open Source Support* (MOSS) project funds tons of OSS projects worldwide.  It has a $10,000.00 to $250,000.00 payout on a _quarterly_ basis.

### Tasks

- [ ] Update White Papers for ELMS:LN
- [ ] Create White Paper for OpenUlmus
- [ ] Deploy branding site for OpenUlmus
- [ ] Deploy branding site for Drupal Open Learning
- [ ] Complete Application
- [ ] Complete **Schedule of Work** (SoW), as per MOSS reqs
- [ ] Designate an official 'Leader' for the OpenUlmus project

**Brochure Page:** https://www.mozilla.org/en-US/moss/mission-partners/**
**Full Details for Applying:** https://wiki.mozilla.org/MOSS/Mission_Partners 
**Application Form (for review):** https://docs.google.com/forms/d/e/1FAIpQLSe9a9h4afnJnDp3rRRHB4i1Xnb3otzfaQrb9uXVeoeXlB3NSg/viewform
**Forums:** https://groups.google.com/forum/#!forum/mozilla.moss

Both ELMS:LN and OpenUlmus seem to have great potential as projects which the 'Mission Partner' program might just fund:

> "The Mission Partners track is open to any open source or free software project that is undertaking an activity which significantly furthers Mozilla’s mission."

Mozilla's Mission: https://www.mozilla.org/en-US/about/manifesto/ 

## Qualifying

To qualify, we have to meet the following five criteria. They should also be submitted by the designated "Leader" of the project.  (It does not specify whether that 'Leader' should be an individual or can be a Committee, if run-by-committee.)

1. Enhancement
> "The project should be to write or enhance some software or software documentation which is under an OSI open source and/or an FSF free software license (non-software exceptions will be considered on a case-by-case basis)."
2. Project Origin
> "The project’s home can be anywhere in the world where we can make payment without undue burden."

OpenCollective is where payment can be made. No issues there.
3. Usefulness
> "Activities which are not sufficient for an award on their own include: writing open source software (notwithstanding manifesto principle #7); building something cool with web technologies; and translating open source software into another language."

Both ELMS:LN and OpenUlmus *definitely* qualify as 'useful' because they provide a global service to every single OSS community on a global scale.
4. Endorsement
> "The specific project activity should be endorsed (on the application form) by someone well-known and respected in a wider software community of which the project is a part."

I would say @btopro carries that for us alone, even without including anyone else.
5. Mozilla Mission
> "The project should benefit Mozilla’s mission. This is normally demonstrated by tying the objective of the project to specific Mozilla manifesto principles or other demonstrated priorities."

## Completion

There *ARE* a few other items to consider.

> "The application form has an "Outcomes" section, and any award will require a contract or agreement with a Schedule of Work (SoW) which defines what work is to be done. Both of those things might benefit from examining a sample Schedule of Work."

## Deadline

The most recent deadline for application was October 31, 2017. As they are awarded quarterly, the deadlines are as follows:
- January 31, 2018
- April 30, 2018
- July 31, 2018
- October 31, 2018
