### ISSUE TITLE
Branding Site: Feedback and Post-Launch Cleanup

### ISSUE THREAD

**Issue by cleverington** [elmsln/openulmus.org#34]
## Feedback
Our site has finally launched!  See it live at https://openulmus.org/ 

Now that it has launched, though, there are obviously areas where we can iteratively improve the site. 

Add your *actionable* feedback (with recommended resolution!) via comments and we'll get it fixed up super-quick.

### Tasks
- [x] **Header** ( PR #53 )
  - [x] Courses link - need to fix 
  - [x] Team link - need to fix 
- [ ] **Marketing copy**
  - [ ] Mission/About Open Ulmus - should we revise/consolidate into header section? [(see the google doc)](https://docs.google.com/document/d/11Wz3Qj1IVZHkbDzi0mi4eee4r-ulkh3Qs6pmHB5RIoY/edit?disco=AAAABjkeSj8)
  - [ ] Open Ulmus | An ELMS:LN Project - should we take out the copy that references the upcoming service? [(see the google doc)](https://docs.google.com/document/d/11Wz3Qj1IVZHkbDzi0mi4eee4r-ulkh3Qs6pmHB5RIoY/edit?disco=AAAABjkeSj8)
- [x] **Courses** Section https://github.com/elmsln/openulmus.org/issues/34#issuecomment-349829279 ( PR #53 )
  - [x] Intro to xAPI https://courses.openulmus.org/xapi/ 
  - [ ] Developer bootcamp https://courses.openulmus.org/dbc
  - [x] Intro to ELMS:LN https://github.com/elmsln/openulmus.org/issues/6 (under development)
   - [ ] Intro to Drupal Open Learning https://github.com/elmsln/openulmus.org/issues/14 (under development)
    - [x] Intro to Drupal Dojo (under development)
- [x] **Our Team** Section
  - [x] Remove Bios from **Our Team** section
  - [x] Update Social Media Links for **Our Team** section
  - [x] Add other Team Members to **Our Team** section (and make sure they are on OpenCollective/openulmus, as that is where we draw avatar icons from)
    - [x] @kat-wehr  (permission received)
    - [x] @btopro  (permission received)
    - [x] @michael-collins (permission received)
    - [x] @djfusco (permission received)
- [x] **Support Our Team** Section (PR #52 has good resolution. OpenCollective loads their own thing. )
  - [x] Add **Support Our Team** section below  **Our Team** section https://github.com/elmsln/openulmus.org/issues/34#issuecomment-350411523 (included in #52 )
    - [x] Add Sponsors
       - [x] Platinum Sponsors
       - [x] Gold Sponsors
       - [x] Silver Sponsors
       - [x] Bronze Sponsors
    - [x] Add Backers
- [ ] **Get In Touch** - do we need the 'Need more information? Reach out to the Open Ulmus team using the following methods.' blurb?
  - [ ] Find us online / Office hours - can we use the icons? are we really running office hours? https://github.com/openulmus/openulmus.org/issues/34#issuecomment-345871931
  - [ ] Contact Form - wouldn't it read better as 'Contact Us'? 
- [x] **Footer** (PR #53 )
  - [x] Blog link - need to remove or fix
  - [x] About link - need to remove or fix

### Out of current scope
- [ ] **Our Collectives** Section
  - [ ] Add Our Collectives section?  Thoughts? <---- **FEEDBACK / THOUGHTS**
- [ ] **Our Projects** Section
  - [ ] Add **Projects** Section above the **Our Team** section using the same functionality
  - [ ] Add Open Learning Labs (Once Branding Site exists)
  - [ ] Add Drupal Open Learning Labs (Once ELMS:LN install or Branding Site exists)
  - [ ] Add Drupal Dojo (Once ELMS:LN install or Branding Site exists)
- [ ] **Pricing**
  - [x] Update 'Prices' link to read 'Pricing'
  - [x] Remove 'Pricing' section until it can be reviewed and approved -> Moved to PR #36 
  - [ ] Review and Update 'Pricing', as needed ( task for @mmilutinovic1313 & @cleverington )

**Comment by gusaus** [comment]
I swapped the order a bit to reflect really quick changes we can make to live site. Beginning with the "Team" section here are some quick suggestions - 

![open ulmus an elms ln project open ulmus 2017-11-20 14-17-30](https://user-images.githubusercontent.com/113996/33044365-8d067628-cdfd-11e7-920b-190ae1df4a7b.png)

With regards to team members, I'm thinking we should list those who have an active or confirmed role in active projects or supporting the platform. @btopro @kat-wehr @michael-collins @djfusco and ....?

**Comment by gusaus** [comment]
Some notes on the course section - 

![open ulmus an elms ln project open ulmus 2017-11-20 14-53-15](https://user-images.githubusercontent.com/113996/33045669-8ad14bd0-ce02-11e7-9f5d-0a58baefccb4.png)

Not sure we need this section until we have a couple live courses to display. Thoughts?

**Comment by gusaus** [comment]
Few comments regarding the footer....
![open ulmus an elms ln project open ulmus 2017-11-20 15-47-22](https://user-images.githubusercontent.com/113996/33047353-1ab554b0-ce0a-11e7-93a9-8e162c9c453b.png)

**Comment by cleverington** [comment]
@gusaus Some thoughts.

## Team

I'm good with all the recommended changes, including adding each Team Members preferred social media.

## Courses

We should move this content into a development branch (including a req to set out a defined height/width for consistency) and bring the content back in as it goes live. 

## Footer

**Footer Links** - I plan on shifting much that content into a `development` branch.

On the powered by ELMS:LN, I would prefer to add that as a component somewhere on the page instead, in _addition_ to the Grav CMS.  Part of the Ulmus is respecting the culminated OSS projects which has built is, so it seems counter-intuitive to remove acknowledgement of GravStrap. Though, I would include a note we are powered by a Gravstrap *sub* theme.

**Comment by gusaus** [comment]
Thoughts on these thoughts? 

![open ulmus an elms ln project open ulmus 2017-11-20 16-01-09](https://user-images.githubusercontent.com/113996/33047708-0878997c-ce0c-11e7-8777-eefe3161a5e1.png)

**Comment by gusaus** [comment]
@cleverington 

> We should move this content into a development branch (including a req to set out a defined height/width for consistency) and bring the content back in as it goes live.

Sounds like a very good idea for anything we can't revise/tweak in the very short term.

**Comment by gusaus** [comment]
Are all the current team members https://github.com/elmsln/openulmus.org/issues/2 good with being listed on the site? https://openulmus.org/

cc  @btopro @kat-wehr @michael-collins @djfusco

**Comment by btopro** [comment]
fine here

**Comment by gusaus** [comment]
Some feedback on "Our Projects Section" as listed out https://github.com/elmsln/openulmus.org/issues/34#issue-275238070

What is an Open Ulmus project? 

Is it a course? If so, we're currently just working on ELMS:LN Open Ulmus Course https://github.com/elmsln/openulmus.org/issues/6  

Is it a white label instance of Open Ulmus? If yes, we could add projects that @mmilutinovic1313 has checked off https://github.com/openlearninglabs/administration/issues/6 

Seems like 'projects' would just be the latter. So Drupal Open Learning and Drupal Dojo would be the first 2 we could list.

Thoughts?

**Comment by gusaus** [comment]
Some feedback on "Our Collectives Section" as listed out https://github.com/elmsln/openulmus.org/issues/34#issue-275238070

Open Ulmus has just the one collective https://opencollective.com/openulmus and we should definitely embed the widgets that display sponsors & backers (possibly hold off until we have more than one!) https://github.com/opencollective/opencollective/wiki/Show-Backers-and-Sponsors 

Better yet, incorporate Polymer for a better handle on how we display widgets https://github.com/opencollective/opencollective-api/issues/769

This would all be in the sponsor/backer section.... not sure we need an 'Our Collectives'

**Comment by djfusco** [comment]
okay with me.

**Comment by michael-collins** [comment]
Fine with me as well.

**Comment by mmilutinovic013** [comment]
@cleverington - let's work together on pricing this week. We can also make sections for all the other sub-issues. I wanted to ask @gusaus if dojo and the open learning labs have logos we can / should use?

**Comment by gusaus** [comment]
Just want to make sure we're clear regarding what courses to display. I 'think' we agreed any live or under development courses would be in scope. That would include - 

- [x] Intro to xAPI https://courses.openulmus.org/xapi/ 
- [ ] Developer bootcamp https://courses.openulmus.org/dbc
- [x] Intro to ELMS:LN https://github.com/elmsln/openulmus.org/issues/6 (under development)
- [ ] Intro to Drupal Open Learning https://github.com/elmsln/openulmus.org/issues/14 (under development)
- [x] Intro to Drupal Dojo (under development)

In terms of displaying, some slight modifications of something like https://webpack.academy/ could work - 
![home webpack learning academy 2017-12-06 17-13-23](https://user-images.githubusercontent.com/113996/33693638-c55fc9fe-daa8-11e7-9677-a52d9f56a232.png)

Thoughts?

**Comment by mmilutinovic013** [comment]
Yep XAPI is live - I have to create an issue about fixing media.openulmus.org (#49)

**Comment by mmilutinovic013** [comment]
Is @ikit-claw still a part of this project, @gusaus & @cleverington? If so we can add him to the site with permission -- if not I'll delete the space on the issues!

**Comment by gusaus** [comment]
I think we can clean up the way we're displaying Open Collective sponsors and backers. What do you think about replicating https://webpack.js.org/

![webpack 2017-12-08 17-05-17](https://user-images.githubusercontent.com/113996/33790948-f891d6ae-dc39-11e7-884b-ffbd50f996c3.png)
![webpack 2017-12-08 17-07-43](https://user-images.githubusercontent.com/113996/33790974-50647b0c-dc3a-11e7-8f69-4b11687c8341.png)
![webpack 2017-12-08 17-09-28](https://user-images.githubusercontent.com/113996/33790992-8f8f699a-dc3a-11e7-84bb-c8c15dc9c2c4.png)
![webpack 2017-12-08 17-10-48](https://user-images.githubusercontent.com/113996/33791014-bebb46da-dc3a-11e7-9f44-641b13277176.png)
![webpack 2017-12-08 17-11-43](https://user-images.githubusercontent.com/113996/33791021-dfcc3de8-dc3a-11e7-8d89-c18f6e08222c.png)

**Comment by gusaus** [comment]
I made a bunch of notes and referenced additional comments in the above task list https://github.com/elmsln/openulmus.org/issues/34#issue-275238070

Make sure to check the references to the google doc regarding marketing copy.

Would be great if we make quick fixes to the links and then brainstorm/solidify both the copy and the perks in the google doc.

**Comment by gusaus** [comment]
Couple notes on the 'support' section - 

![open ulmus an elms ln project open ulmus 2017-12-12 21-08-37](https://user-images.githubusercontent.com/113996/33922583-9ff4232c-df80-11e7-9607-cc225e68650a.png)

Is there a reason we couldn't format more like https://github.com/openulmus/openulmus.org/issues/34#issuecomment-350411523?

**Comment by gusaus** [comment]
I provided a few more rounds of feedback and made notes in the task list https://github.com/openulmus/openulmus.org/issues/34#issue-275238070

Aside from mainly cosmetic issues, it's mainly the a question regarding how much/little we should be referencing the future service at the moment (see my confusing comments in 'marketing copy' section). Personally I think we should keep the focus primarily on Open Ulmus, as a child OSS project of ELMS. 

We can/should certainly blog, tweet, run ongoing Dojo sessions/sprints/etc as way to keep potential supporters and contributors looped in as we progress. I'm just not sure that saying we'll providing a service (or directing to a partner like Open Learning Labs before that's ready) will be a selling point to those who aren't already familiar with ELMS:LN and the amazing team (aside from myself) that's representing! 

The other thing to keep in mind is we have at least 3 Open Ulmus related solutions already queued up to carry us into the new year!  https://github.com/openlearninglabs/administration/issues/6#issue-277957596

Would be great to have feedback from the rest of the team! @btopro @kat-wehr @michael-collins @djfusco

**Comment by cleverington** [comment]
@gusaus It is a work in progress.

The current Support section from OpenUlmus loads by a si gle script tag.

I was actually planning on moving your comments into a separate issue last night for the stuff which is a little more complicated. I am either going to have to find a module that can support our support section's content, find one that is already _installed_ and how to put it to better use, or create my own.

I just didint spin it off last night cause I got busy with launching the updated content.

I also want to flip xAPI to be the FIRST card, considering it is the only ome working and a clickable link.

We also need to discuss / decide on those Office Hours and whether to straight up remove it for now until we have a confirmed schedule outlining attendance and devs/admins available to answer installation, co figuration, and debugging questions.  Personally, I say leave it, but add notes that Sponsorship will make it happen.

**Comment by cleverington** [comment]
Second piece of feedback is the Courses themselves. I added those cards as sort of filler content until we can create a standard height / width / layout / etc. on the cards. You'll notice they definitely are not perfect.

If anyone has any thoughts / feedback on those cards, would love it.

Also, need 'Coming Soon' landing pages for both in-development courses that we can link to.

**Comment by gusaus** [comment]
@cleverington Thx - just wanted to provide more feedback as I know we want to focus back on other complementary projects. 

Assuming it would take little time to add back in, I'd be on the side of removing anything (like office hours) that team listed on the site is currently unable to deliver. We could potentially have  mentoring/office hours tier on the Open Learning Labs collective and link to that in the near future. 

Followup questions/thoughts on displaying courses & sponsors - 

@btopro Is there any sort of polymer, webcomponent or other magical gizmo thing that could give us better control/display of the courses? https://github.com/openulmus/openulmus.org/issues/34#issuecomment-349829279

Similar thing for displaying backers/sponsors? https://github.com/openulmus/openulmus.org/issues/34#issuecomment-350411523

With regards to linking to courses in progress.... what if each course was developed in it's own repo on https://github.com/openulmus/ - if we went that route, we could create a collective for each course and allow people/orgs to fund it! 

Definitely should create an issue to explore a collaborative course dev/funding process, but some of the workflows here provide some divine inspiration -  https://about.gitlab.com/2017/10/12/collaborative-course-environment-gitlab-grav/

**Comment by btopro** [comment]
https://www.webcomponents.org/element/PolymerElements/paper-card is what we've used previously; it's a nice pretty standard convention for a window into what the thing is. Could even pop open via paper-dialog to provide more details

**Comment by gusaus** [comment]
Seems like that could work well for courses, ya? Also would unify the experience a bit if we're using a Drupal based site for Drupal Open Learning.

And implantation might make for a nice Drupal Dojo mini session!

Thoughts on that @mmilutinovic1313 @cleverington ?

**Comment by gusaus** [comment]
Quick followup to @btopro regarding Polymer https://github.com/openulmus/openulmus.org/issues/34#issuecomment-351609807

Are there any recommended options for exporting sponsor/backer data into an element?
https://opencollective.com/openulmus/edit#export <-- provides us with a few export options

Is there anyone interested/well versed enough to create one as a teachable moment?

**Comment by btopro** [comment]
oh https://opencollective.com/openulmus/members/all.json into a `<template is="dom-repeat">` would be super easy to generate a list

**Comment by btopro** [comment]
what's the target as far as being a teachable thing?

**Comment by gusaus** [comment]
I'm just thinking we could turn any cool new feature or integration into a Drupal Dojo session anytime. Several communities (Drupal, ELMS:LN, Grav,...even Open Collective) would wanna get involved with all the amazing!

**Comment by btopro** [comment]
gotcha; I know several people capable of turning that into something; it's a matter of who, when, etc. @mmilutinovic1313 asked me about doing a dojo session; I could probably swing that end of next week or week after and do this or something more elms:ln related to polymer

**Comment by btopro** [comment]
I almost have HAX working for D6 and D7; working towards backdrop today; D8 isn't hard but I just don't support it at this time so not sure how helpful something on that would be (unless it was; "look how easy this is to integrate into any CMS,.... someone plz do D8 :))

**Comment by gusaus** [comment]
>D8 isn't hard but I just don't support it at this time so not sure how helpful something on that would be (unless it was; "look how easy this is to integrate into any CMS,.... someone plz do D8 :))

@btopro If you were able to do a quick Dojo session/demo on how you set up D7, we could also use that as a call for D8 help and really whatever/whoever else we need.

Similar thing for Polymer and OpenCollective. The elements(?) OpenUlmus needs may also be useful for https://www.elmsln.org/ and any other project incorporating OpenCollective in the ELMS:LN.

As I don't know how long any of this will take (we should get all this into the project scope https://github.com/openulmus/openulmus.org/issues/1), if there's somebody who can do a quick implentation and demo, we can again use that as an opportuntity to ask for contributors and contributions. Actually could be a really good way direct attention/funders to our collectives.

**Comment by btopro** [comment]
hmmm ok. so like a thing about setting up Webcomponent based development in D7 using the webcomponent module, HAX (which I just got mostly working), and then showing some custom development w/ polymer which uses opencollective data as the backend to present user info.

This is all stuff I'd be totally game for, especially since I"m going to have to start documenting in blog posts, videos and writing wtf HAX is, how it works, how you can leverage it in different systems.

**Comment by gusaus** [comment]
If D7 is more ready to go, maybe we could start by spinning up an OpenProducer (D7/Panopoly based) instance for the Drupal Open Learning branding site. We should be able to swap out the Pantheon sponsored setup for the current/old http://drupalopenlearning.org/

Along with making sure we include features/functionality in the project scope, we should list out any human helpers that we may still need (mentors/apprentices for dev, docs, training, producing vids, blog posts, sprints/events etc.).

**Comment by gusaus** [comment]
@btopro Based on https://www.youtube.com/watch?v=EazgwOcQ2EI, it looks like we'd be able to display our courses similar to the example in https://github.com/openulmus/openulmus.org/issues/34#issuecomment-349829279 with HAX

If this is the case, do we have HAX already plugged into this Grav site? or do we need to update and include https://github.com/elmsln/grav-plugin-hax?

**Comment by btopro** [comment]
it's not on there yet but it's some small love (and HAX in general getting more bug fixes) from being a drop in replacement for legacy authoring

**Comment by gusaus** [comment]
@btopro Might this be something interested contributors at DCon could sprint on? If so, we could put it on the Drupal Open Learning sprint agenda!

**Comment by btopro** [comment]
maybe; I'll be there Friday most of sprint day trying to do sprints on HAX with anyone interested.
