### ISSUE TITLE
Open Ulmus Checklist

### ISSUE THREAD

**Issue by mmilutinovic013** [elmsln/openulmus.org#4]
Here are the tasks that need to be completed before the release(s):

- [ ] Define scope for Open Ulmus MVP #1 
- [ ] Define roles for launching, managing and sustaining Open Ulmus #2
- [ ] Discuss cost of courses #5 
- [ ] Build intro to elmsln course #6 
- [ ] Build intro to openulmus course #7 
- [ ] Getting started with drupal course with drupal-dojo folks #8 
- [ ] Build course on a technical topic (Haskel or something) as POC for tutorials we can offer. #9
- [ ] AWS Logistics
- [ ] Look at Docker #10

These can be thrown into different releases but these need to be solved before we move forward. Will make into release plan and create issues for each that will link to here

**Comment by gusaus** [comment]
This is a master checklist for the Open Ulmus release? If so, we may want to add the following - 
 
- [ ] Define scope for Open Ulmus MVP https://github.com/elmsln/openulmus.org/issues/1
- [ ] Define roles for launching, managing and sustaining  Open Ulmus https://github.com/elmsln/openulmus.org/issues/2

**Comment by mmilutinovic013** [comment]
Yessir - adding those.

**Comment by mmilutinovic013** [comment]
Closing this as a duplicate as we are defining releases in a different manner now.
