### ISSUE TITLE
Agenda: 12/04/2017

### ISSUE THREAD

**Issue by cleverington** [elmsln/openulmus.org#45]
### 1. High level org and sustainability discussion
- [ ] Open Learning Labs scope of service offering https://github.com/openlearninglabs/administration/issues/1
  - [x] How Open Learning Labs supports Open Ulmus projects, but not the service
- [x] Open Learning Labs short term sustainability plan https://github.com/openlearninglabs/administration/issues/5
  - [x] Helping develop and support white label Open Ulmus MVPs are in-scope https://github.com/openlearninglabs/administration/issues/6

### 2. Open Ulmus platform and white label instances: Status & Discussion Tasks
- [x] [MVP for Open Ulmus](https://github.com/elmsln/openulmus.org/issues/1)
  - [ ] Initial fundraising plan #22 
  - [x] ELMS:LN Open Ulmus Course #6 ( @kat-wehr )
  - [x] Initial ELMS:LN Training Course Outline #29 ( @kat-wehr )
  - [x] Logo Design #26 ( @michael-collins )
  - [x] Branding Site: Feedback and Post-Launch Cleanup #34 
  - [x] Branding Site: Administrative Plugin #35 
- [x] Open Learning Labs money flow process https://github.com/openlearninglabs/administration/issues/4
- [x] [MVP for Drupal Open Learning relaunch](https://github.com/DrupalOpenLearning/drupalopenlearning/issues/1)
- [x] [MVP for Drupal Dojo relaunch](https://github.com/DrupalOpenLearning/drupaldojo/issues/4)

### 3. Open Ulmus service offering: Status of Organization
(eg: Making OpenUlmus a recognized 'Organization' and how to make those steps)
- [x] Move service related code off of `elmsln` repository to provide accurate separation. What repository to use? 
  - https://github.com/openulmus?
- [x] Open Ulmus service as a stand alone collective (OpenCollective would be the host org)

### 4. Open Ulmus service offering: Fundraising and sustainability
- [x] Title for Open Ulmus hosted service #30 
- [x] Client Branding/Marketing Sites: myproject.org #32 - Status and discussion. Will need to Fork/Parent a copy of current OpenUlmus.org
- [ ] ($) Tiers for Courses #24 
- [x] Fundraising: MOSS - Mission Partners #33 
- [ ] Communities to Contact #40

### 5. Open Ulmus service offering: Pricing Plans, White Paper, & Prospectus
We need a Prospectus
Ask @michael-collins -> What is the status of the White Paper update?
We'll be leveraging the look/feel of the White Paper for branding look/feel, so we should make sure the Prospectus looks similar.
**Example Prospectus:** https://drive.google.com/drive/folders/0B8JYyp1JZX7JejEyTzdtNlJiSHc -> texascamp sponsor.pdf

- [x] White Paper - https://github.com/elmsln/elmsln/issues/2321
- [x] Prospectus - #43 
- [x] Pricing Page (on openulmus.org GravCMS)
- [x] Pricing Page (on Wiki)

### 6. Closing discussion and Notes on Actions/Commitments on Funding Sources / Actions
What endeavors is everyone embarking upon for the next two weeks.

### 7. Resources Page
Following this thread/comment -> https://drupal.slack.com/archives/C5NR9LLNT/p1512440169000047
It would be beneficial to have a unified 'Resources' page under OpenUlmus (or the Wiki) with references to _current_ ELMS:LN resources. Part of the difficulty with onboarding right now is the scattered state of the resources.

### 8. Closing Discussion
Further comments, feedback, plans.
- [x] Quick Question: Theming on courses.openulmus.org / online. / etc.? Cause we could REALLY use some FE work.

**Comment by gusaus** [comment]
I added titles and shuffled the agenda items around. Will add detail to the high level org and Open Ulmus platform items tomorrow. 

Personally I think it would be 'less' overwhelming if we left anything related to 'Open Ulmus service offering' until we have the resources (platform, staffing, org/biz plan, etc) to sustain. 

Open Ulmus platform and white label instances should provide the program and platform teams short term funding in the interim.

**Comment by mmilutinovic013** [comment]
Closing Discussion question would be a good question for @btopro, @heyMP, or @michael-collins.

**Comment by michael-collins** [comment]
I was not aware that I was supposed to be updating the white paper. I will not have time to do this until maybe... February.

**Comment by mmilutinovic013** [comment]
@michael-collins - To my knowledge, we never approached you about updating the paper so no worries! :). I believe this was intended to be a discussion on what content might be beneficial to have updated within the paper. I will relay this information to you for when you have more time in the future!

**Comment by mmilutinovic013** [comment]
Another summary around UX - https://github.com/elmsln/elmsln/issues/2344#issuecomment-349268869 -- It's coming soon.

**Comment by cleverington** [comment]
## Meeting Minutes - 2017-1205

### Attendance
- Gus Austin (@gusaus)
- Mark Milutinovic (@mmilutinovic1313)
- Charles Leverington (@cleverington)

### Discussion

#### 1. High Level Org and Sustainability Discussion
- Gus: Open Learning Labs is a Service on top of / using Open Collective to sustain Open Source Projects.
- Gus: One of those **projects** is the OpenUlmus **Project**, but would not support/provide for the OpenUlmus **Paas**
- Project Reference: https://gitlab.com/openproducer/openproducer 
- Gus: We have an existing Collective (OpenUlmus, DrupalDojo, etc.), who could be funded/sponsored in order to develop MVP
- Gus: **Use Case Example:** Using Open COllective, we could pre-sell a year's white-label project for "Example Project", paid by a given Sponsor directly as a Donation within Open Collective. (In this context, a white-label would be online.myproject.org / courses.myproject.org)
- Reference for Potential Sponsor / Partner: https://opencollective.com/grav
- Mark: Are we at a point where we can approach the GravCMS community and say "We'd like to collaborate and build you xxxxxxxxx".
  - Answer: No. We need to focus on direct funding for OpenUlmus, possibly using Sponsorship of DrupalDojo by big-name Vendors like Acquia, Pantheon, Aegir, etc.
  - Gus: We need to focus on current / direct funding for OpenUlmus
- Gus: We want to create a standalone child distribution of OpenSocial and integrate it with ELMS:LN as _part_ of the OpenUlmus project and Drupal Dojo.
- Gus: We should also think on scheduling Sprints.
- Charles: What task-items should we finalize in the next two weeks to help complete item #1.
- Gus: The site for Drupal Open Learning would be the first white label instance _using_ the OpenUlmus project.
- Gus / Charles: We'll need a branding / showcase project on DrupalOpenLearning.
- Gus: We should just straight-up clone what exists on/at openulmus.org, which can be referenced / used / showcased to the Drupal Community.
- Task for Mark: Workflow on how to clone what exists on OpenUlmus.org to DrupalOpenLearning.org.
- Gus: Task for Mark: https://github.com/elmsln/openulmus.org/issues/21 (edited)
- Gus: We should have a _Team_ in charge of creating instances.
- Gus: We should use the corresponding rooms in http://drupalslack.herokuapp.com/ for collab on all of the above projects.

##### 1. Tasks
- [ ] Get **Drupal Open Learning** Branding Site Online
  - [ ] Open Learning Logo?
  - [ ] Create Branding/Showcase Parent GravCMS installation - @cleverington - #32
  - [ ] Create child-install of GravCMS for Drupal Open Learning - @cleverington - #32
  - [ ] Workflow Document / Instructions on how to clone what exists on https://openulmus.org to https://DrupalOpenLearning.org
  - [ ] #21 - @mmilutinovic1313

#### 2. Open Ulmus Platform and White Label Instances: Status & Discussion Tasks
- #6 -> Kat will have time over Xmas break to work on the Open Ulmus Course, which an outline already exists.
- See previous for #29
- Logo Design -> #26 -> Powered by ELMS:LN is a placeholder. Probably looking at February, at the earliest, for logo creation. Mark will reach out to see if a sooner date can be accomplished.
- Charles Task: Remove 'Courses' section, as it doesn't really work in the flow.  Courses =/= Projects in this context.
- Charles Task: Match Projects to https://github.com/openlearninglabs/administration/issues/6 (edited)
- Research Question / Task for ELMS:LN:  Can we have a class which exists on ReactOpenLearning for Git and GitHub which is ALSO available on DrupalOpenLearning with the same branding, etc
- Mark: If OpenUlmus exists as a bunch of different AWS instances, the Courses would have to be exported / imported across projects.  If this is going to be a _single_ *huge* project all being hosted for OpenUlmus, could just have the same Course checked 'Available' on multiple projects.
- Charles Tasks: Re-Add removed 'Courses' section (as _actual_ Courses) which we have under development.
- Gus: Follow task on leveraging the Intro Courses as both documentation and instruction on getting users onboarded.
- Task for Mark: Summarize discussion on two different fiscal approaches in this issue: https://github.com/elmsln/openulmus.org/issues/22
- Create initial fundraising plan · Issue #22 · elmsln/openulmus.org
- This issue tackles finding funds for Open Ulmus through open collective and other crowdsourcing platforms. We to find a way to support our daily operational costs through a collective. Issues that ...
- MVP for Drupal Dojo Discussion
- Need to start picking up on the Project management for the Drupal Dojo project again.
- Task for Charles: Start outlining a completed Project Scope.
- Task for Charles: Start outlining workflows for End-User groups (such as Austin Drupal Dojo).
- Task for Charles: Cleanup the Drupal Dojo site and configuration.
- Task for Charles: Create a proof-of-concept group on Drupal Dojo for DDI-Contrib team to give them an events/etc. area.
- Task for Charles: Start outlining required documentation.
- Task for Gus: Take tasks from this thread and either email to Charles, add to Asana, or add to a GitHub Project.
- MVP for OpenUlmus -> Will review at/around January 1, after final MVP tasks are completed.

##### 2. Tasks
- [ ] OpenUlmus.org Branding Site Changes
  - [ ] Remove 'Courses' section, as the current _version_ of it does not work in the flow (or match the correct context) - @cleverington
  - [ ] Match 'Projects' section to https://github.com/openlearninglabs/administration/issues/6 (with details) - @cleverington
  - [ ] Re-Add 'Courses' section to match project workflow, referencing those Courses actually under development - @cleverington
- [ ] OpenUlmus
  - [ ] Get clarification from @btopro:  - @mmilutinovic1313
  Can we have a class which exists on the **React Open Learning** site and also available on the **Drupal Open Learning** site, without having to recreate? Maybe a field where the 'Groups this Course applies to' occurs or something?
  
  (Think Courses like Git Intros, GitHub Intros, etc., where we shouldn't be re-inventing the wheel over and over again, but would still like to have the Course seem to be "Community Specific")
  
  (**Note:** This task is one which may involve a _**required**_ major-implication infrastructure decision, which may require input from the full ELMS:LN team.)
- [ ] Sustainability
  - [ ] Summarize discussion on two difference fiscal approaches, as we discussed during the meeting, in #22. - @mmilutinovic1313
    - [ ] Approach #1: Microtransactions
    - [ ] Approach #2: Quasi-Contracted Development, as per Sponsor/Client request, with specified hours, project goals, and roadmap
- [ ] MVP for Drupal Dojo Discussion
  - [ ] Finish outlining a completed Project Scope for Drupal Dojo relaunch - @cleverington
  - [ ] Start outlining workflows for onboarding End-User groups (such as Austin Drupal Dojo) - @cleverington
  - [ ] Create proof-of-concept **Group** on current Drupal Dojo installation for DDI-Contrib team to give them Events, Scheduling, Mentoring, etc. - @cleverington
  - [ ] Start outlining required documentation - @cleverington

#### 3. Open Ulmus service offering: Status of Organization
- Moving elmsln/openulmus.org to openulmus/openulmus.org:
- Task for Mark: Reach out to @btopro and ensure he is okay with moving the repository from the `elmsln` organization into the `openulmus` organization.
- (from @btopro) yes
- (from @cleverington) @btopro No, no, no no! @mmilutinovic1313 hasnt reached out yet!!! Meow you've gone and done it....

##### 3. Tasks
- [ ] Moving elmsln/openulmus.org repository to openulmus/openulmus.org repository
  - [x] Reach out to @btopro and ensure he is okay with moving the repository from the `elmsln` organization into the `openulmus` organization - @mmilutinovi1313 (Answer Already Received: Yes)
  - [ ] Next Meeting Agenda Task-Item: Separating 'Administration' tasks and **Branding Site** tasks within the `openulmus` GitHub Organization.
  - [ ] Move `elmsln/openulmus.org` repository to `openulmus/openulmus.org` - @cleverington

#### 4. Open Ulmus service offering: Fundraising and Sustainability
- #30 -> Shelving till over xmas
- #32 -> Create the fork for the GravCMS branding/marketing project on github.com/openulmus
- Task for Charles: #32
- #24 -> Shelving. Courses will not be on openulmus.org, but will be on something like the drupalopenlearning
- #33 -> (Gus) Let's focus on getting the Tiers down and done on the Marketing sites.
- #33 -> Try and put either Michael or Bryan on approaching this task.
- #40 -> Gus is tackling

##### 4. Tasks
- [ ] #32 - @cleverington
- [ ] #33 - MOSS Fundraiser - @mmilutinovic1313 -> Try and get either @btopro or @michael-collins on this task to (with any luck) get enough funding to remove the current blockers.
- [ ] #40 - Groups to approach and request Sponsorship - @gusaus

#### 5. Open Ulmus Service Offering: Pricing Plans, White Paper, & Prospectus
- https://elmsln.readthedocs.io/en/latest/development/Vagrant-Step-by-Step-setup/
- https://www.elmsln.org/documents
- ^ White Paper lives here and resources for white paper = top link
- Prospectus -> Requires White Paper update.
- @mmilutinovic1313 Those documents are mostly 2+ years out of date and/or no longer available. :wink:   And the elmsln.readthedocs is also semi-outdated / not updated.
- Task for Mark / Gus: Pricing Page -> Will begin consolidating pricing information. Once finalized, will add them to Open Collective page and copy to the GravCMS page.
- Task for Mark / Gus: Document the Workflow for three example Clients.  One big, one mid-sized, and one very small.

##### 5. Tasks
- [ ] Pricing Page - @gusaus & @mmilutinovic1313
  - [ ] Consolidate Pricing Information into completed document
  - [ ] Update OpenCollective with Pricing / Donation Plans
  - [ ] Update GravCMS ( https://openulmus.org/ ) with Pricing / Donation Plans
  - [ ] Update Wiki wtih Pricing / Donation Plans
- [ ] Document Workflows on Use Cases - @gusaus & @mmilutinovic1313
  - [ ] Small Client/Sponsor Use Case
  - [ ] Mid-Sized Client/Sponsor Use Case
  - [ ] Large-Sized Client/Sponsor User Case
- [ ] White Paper & Prospectus
  - [ ] Update White Paper - @mmilutinovic1313 will review
  - [ ] Create Prospectus - for handing out to potential Sponsors
  - [ ] Create Sponsorship 'Template' Email - For approachign potential Sponsors

#### 6. Closing Discussion and Notes on Active / Committments on Funding Sources / Actions
- OpenCollective / DrupalDojo -> Will be going for Tiers / levels of Sponsors and want to get activity going on DrupalDojo to get Sponsorship.

##### 6. Tasks
No Tasks

#### 7. Resource Page
- Task for Mark: Create the Wiki page
- Task for Charles: Create an issue.

##### 7. Tasks
- [ ] Resource Page / Link-Farm
  - [ ] Create an issue to have Wiki page of Link-Farm created - @cleverington
  - [ ] Create a link-farm of ELMS:LN resources / tutorials / videos (which are **valid** and **active** ) for Branding site and/or Wiki page - @mmilutinovic1313

### Global Tasks
- [ ] Create BurnDown Task Lists for Sprinting
- [ ] Schedule Sprints for January

**Comment by cleverington** [comment]
Meeting Minutes added in previous comment.

Will convert to a Wiki page on https://github.com/openulmus, once site-repo from `elmsln/openulmus.org` is moved to `openulmus/openulmus.org`.
