### ISSUE TITLE
Determine cost and scope of internal courses

### ISSUE THREAD

**Issue by mmilutinovic013** [elmsln/openulmus.org#5]
Opening and (poorly) rewording this issue to reflect the scope of classes in which we'll create documentation, guidelines, case studies, and other learning experiences derived from building and operating internal sites. 

Should/could we include these types of deliverables in the overall scope of these projects?

**Comment by mmilutinovic013** [comment]
Closing this as a duplicate as OpenProducer/newspack-platform#20 exists

**Comment by gusaus** [comment]
Another goal of this issue (which I didn't really clarify in the description) is to estimate how much budget would be needed to keep a team active on a given project ongoing. For example would it be realistic to secure enough funds to keep a team of 4 spending 5hrs/wk (or per/hat https://github.com/elmsln/openulmus.org/issues/2#issuecomment-338069402) on Open Ulmus? What if we could do the same for Drupal Open Learning, Drupal Dojo, and one other internal project.  Each team member, assuming they had an identical role on each project, would have a budget for 20hrs/wk (at a TBD competitive rate) just for internal projects.

Possible?

**Comment by mmilutinovic013** [comment]
I like this model as it will allow for a structured approach (for now) on how these courses will be run financially (for people). AWS is a whole different ballgame - and I believe is separate from this issue.

**Comment by gusaus** [comment]
I added OpenProducer as it's an existing project that we also control. We also have a service model to sustain that we've been putting on hold https://github.com/OpenProducer/administration/issues/3

Based on the projects and people coming together now, I'm thinking one large service umbrella may be the best way to consolidate resources. https://github.com/elmsln/openulmus.org/issues/12

**Comment by mmilutinovic013** [comment]
Yes - the service umbrella is the best idea I think. Do we have an existing umbrella with money that can provide the flow described in the open producer issue? Or would we be starting from scratch? If we are starting from scratch I'd recommend using the model I put together in OpenProducer/newspack-platform#18 combined with the open producer model you listed.

**Comment by mmilutinovic013** [comment]
Shall we talk about perceived costs ($$$) offline? Or is here fine? At the very least I know that AWS will eventually be in the ~$1k+ range a month as a cost for each (or one) of these platforms. For now it sits ~$10 a month

**Comment by gusaus** [comment]
I forget the lingo -  is an instance of ELMS/Open Ulmus a course? @btopro  ~$1k+ range a month as a cost for each or Open Ulmus as it scales up with lots of courses? https://github.com/elmsln/openulmus.org/issues/5#issuecomment-339184784

**Comment by gusaus** [comment]
@mmilutinovic1313 If your talking about hourly rate per role, is there a range that we can attach to each hat? Same range for all roles?  https://github.com/elmsln/openulmus.org/issues/2#issuecomment-338069402

**Comment by mmilutinovic013** [comment]
@gusaus I believe the $1k+ range is for as Open Ulmus scales up. This would be true for any platforms looking to have an instance of Open Ulmus on their own (with a ton of courses) or living on the Open Ulmus site itself (as it scales)

**Comment by mmilutinovic013** [comment]
I went through a few articles about ranges for hourly rates and I found this post (8 years old) debating drupal consulting rates (https://www.drupal.org/node/487142). The ranges listed include: 

$20-35 USD, entry-level, 6 months to 1 year
$40-55 USD, mid-level, 1-2 years
$60-80 USD, senior-level, 3+ years

I would propose we would advertise the following hourly rates for hats and the apprentice roles beneath:

**Hat-wearing leads:** $40-80 per hour
**Apprentices:** $15-30 per hour

We can min max hours for this as well. Feel free to put in additional input if desired. If this is approved I'll model it out in our costs.

**Comment by btopro** [comment]
@gusaus ELMS:LN would / open ulmus would be a single deploy of the platform. Think of it like a multi-site factory (Aegir but not Aegir). I want a course, I actually create a node which then creates a drupal site (or sites) to match. It's basically a site structuring technique though so imagine instead of 1 topple over monster drupal site you had 100+ small in scope ones.

@mmilutinovic1313 those rates sound reasonable depending on how many hours a week / what the commitment is. I think asking Rick in our private ELMS:LN channel would be a good way to gauge if this range is reasonable (he's hired people on contract work for stuff associated w/ the platform).

I will also say people are more ok w/ rates in this range for pure open source / community building work

**Comment by mmilutinovic013** [comment]
@gusaus @btopro - I checked with Rick and he said the rates are good. We discussed that it might be best for senior roles (which I’d include the hat wearing folks in for now) to start at 50 if budget allows. Do we know when people will be able to be paid for their efforts. I’d like to pass that on to some folks interested in different roles so they understand the commitment.

**Comment by btopro** [comment]
that's a @gusaus question for sure :)

**Comment by gusaus** [comment]
@mmilutinovic1313 With regards to this issue, we're trying to determine an hourly rate that would enable our hat wearing leads to commit a certain amount of regular time to the internal/partner projects we are identifying.

With @cleverington onboard to commit some regular time on some much needed roles and tasks, I think we should first prioritize projects based on short term potential for getting our core team members paid for their availability.  

Availability will vary, but let's say we max out the total weekly time for each person at 10hrs/wk. We should see if we can generate enough funds to cover 40hr/wk total time for a four person project team. 

I'll try to add some specificity later this eve.

**Comment by mmilutinovic013** [comment]
Okay - let me know when you have more of the specifics worked out. Above are the rates that I’ve researched and established as baseline reasonable for the hat wearing roles.

**Comment by gusaus** [comment]
We want to keep in mind again, the initial budget for each project will be generated from sponsor and backer funds via OpenCollective. We'll most likely be asking contributors to pay every month, so team members of a given project will be able to invoice against the collective if the monthly funding goals are met. Sort of like an ongoing retainer. 

Since we're going to be focusing first on launching the MVP before creating any courses, we should prioritize our time and funding goals based on the size or reach of a program. 

We'll need to add specificity to the scope of each project, but this is my proposed goal (using a billable rate of $100/hr to make the math easy). 

- [ ] [Drupal Dojo](https://github.com/DrupalOpenLearning/drupaldojo/issues/4) - 80hrs/$8000 month
- [ ] [Drupal Open Learning](https://github.com/DrupalOpenLearning/drupalopenlearning/issues/1) - 40hrs/$4000 month
- [ ] [Open Ulmus](https://github.com/elmsln/openulmus.org/issues/1) - 40hrs/$4000 month

If we hit those goals, each team member would be able to invoice for a total of 40hrs/month (the amount may vary based on availability) at whatever the high level hat wearing rate we decide.

That probably is a long ass, confusing way to explain that... does that remotely make any sense?

**Comment by mmilutinovic013** [comment]
This sounds reasonable to me! Do we have a list of sponsors and backers that have shown interest already? I know many people overlap between project within the collective. Does that mean that they would pull from each of these collectives if the goal is met? Or does that mean that they would be assigned to work on a specific collective for that week/month/etc.?

**Comment by gusaus** [comment]
Initially I think it would be same program managers referenced in https://github.com/elmsln/openulmus.org/issues/2#issuecomment-340952318. We'll be able to draw from whatever collective has funds (i.e. it's not an all-or-nothing fundraising thing) so the one with the most budget available (which I think could be Drupal Dojo initially) would enable us to spend more (paid) time.

**Comment by mmilutinovic013** [comment]
Should we use the $100 / hr billable rate for budget purposes? Or do we know what the going rate is going to be for the program managers defined? I'm working on the budget proposal now and am looking for the best data to use.
