### ISSUE TITLE
Agenda: 02/06/18

### ISSUE THREAD

**Issue by cleverington** [elmsln/openulmus.org#55]
### 1. Short Role Call
- [ ] a. Attendance
- [ ] b. Confirmation of Team Members and Roles [Wiki: 2. Open Ulmus Core Team](https://github.com/openulmus/openulmus.org/wiki/2.-Open-Ulmus-Core-Team)
- [ ] c. Review of Budget & Sustainability [Wiki:5. Budget and Sustainability](https://github.com/openulmus/openulmus.org/wiki/5.-Budget-and-Sustainability)
- [ ] d. Previous Meeting ( 12/04/2017 ) Tiny-Review - #45 

### 2. Active Tasks
- [ ] a. Initial fundraising plan #22 (Follow-up discussion)
- [ ] b. ELMS:LN Open Ulmus Course #6 ( @kat-wehr - Check-In )
- [ ] c. Initial ELMS:LN Training Course Outline #29 ( @kat-wehr - Check-In )
- [ ] d. Logo Design #26 ( @michael-collins )
- [ ] e. Branding Site: Feedback and Post-Launch Cleanup #34 
- [ ] f. Branding Site: Administrative Plugin #35 

### 3. Resources Page
More of an ELMS:LN type issue, but definitely something to follow-up on. See #45 

### 4. Wrap-Up
- [ ] a. Random Question: Should we be using a channel named `elmsln` for meetings?

     ------

PM in Slack if there are any other Agenda items you'd like to add.
