### ISSUE TITLE
Agenda: 02/20/2018

### ISSUE THREAD

**Issue by cleverington** [elmsln/openulmus.org#59]
### 1. Short Role Call
- [ ] a. Attendance
- [ ] b. Confirmation of Team Members and Roles [Wiki: 2. Open Ulmus Core Team](https://github.com/openulmus/openulmus.org/wiki/2.-Open-Ulmus-Core-Team)
- [ ] c. Previous Meetings ( 12/04/2017, 02/06/2018 ) Tiny-Review - #45 and #55 
  - [ ] 1. Discussion - How to document / maintain Meeting Minutes?

### 2. Active Tasks
- [ ] a. ELMS:LN Open Ulmus Course #6 & #29 ( @kat-wehr - Check-In )
- [ ] b. Logo Design #26 ( @michael-collins )
  - [ ] 1. Review may need needed of current Motto / Goals / Direction: 
- [ ] c. Evaluate 501(c3)
- [ ] d. Meeting Times / Schedule (Open Thread, as not everyone can attend)

### 3. Resources Page
More of an ELMS:LN type issue, but definitely something to follow-up on. See #45 
(Will nix this 'standing' issue/task once we have a bulk-resource other than "Go see btopro's YouTube".)

### 4. Wrap-Up
- [ ] a. Wrap-Up Question: Who do you feel a solid competitor for OpenUlmus is?

     ------

PM in Slack if there are any other Agenda items you'd like to add.

**Comment by gusaus** [comment]
Based on a variety a factors, I'd like to suggest the next meeting be more of a working session where we can close out any outstanding issues and reach consensus on how to approach the next phase.

### Open Ulmus: Phase I
Stuff needed to review, evaluate, and complete before moving on

- [ ] Review Open Ulmus service scope and model to sustain https://github.com/openulmus/openulmus.org/issues/58
  - [ ] Program team is only responsible for managing and sustaining the program
  - [ ] Services (producing classes, providing hosted instances, and even building/maintaining the next phase of Open Ulmus https://github.com/openulmus/openulmus.org/issues/1#issuecomment-369738844) would be done on behalf of Open Learning Labs and other partners https://github.com/openlearninglabs/administration/issues/1
- [ ] Review and complete outstanding post-launch cleanup tasks https://github.com/openulmus/openulmus.org/issues/34

### Open Ulmus: Phase II
- [ ] Review and evaluate this suggested path forward https://github.com/openulmus/openulmus.org/issues/1#issuecomment-369738844
